### ISSUE TITLE
Stablish a BLE connection between the mobile app and the WW120

### ISSUE THREAD

**Issue by victor-wildlife** [wildlifeai/wildlife-watcher-mobile-app#10]

**Comment by Burzo** [comment]
Could we involve Charles into this? Since I have the hardware with me now, would it be possible to perhaps write detailed instructions on how to connect and build everything so that the BLE is ready to be used by the client?

I'm not sure where to start. I tested the board I got with precompiled code that Nordic provides, and I could blink the lights via BLE.

**Comment by victor-wildlife** [comment]
Archiving this task as we will tackle it in #11
